[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Attempted to change value of key "seed" from 69 to 532
[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/Users/jahan/Documents/cardiacdeepsurv/train.py", line 45, in <module>
    config.seed = int(rng.integers(1,9999))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/surv/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 148, in __setitem__
    key, val = self._sanitize(key, val)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/surv/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 251, in _sanitize
    raise config_util.ConfigError(
wandb.sdk.lib.config_util.ConfigError: Attempted to change value of key "seed" from 69 to 532
If you really want to do this, pass allow_val_change=True to config.update()